apiVersion: apps/v1
kind: Deployment
metadata:
  name: sorriso-amigo-db
  namespace: davi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sorriso-amigo-db
  template:
    metadata:
      labels:
        app: sorriso-amigo-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: sorriso_amigo
            - name: POSTGRES_USER
              value: davi
            - name: POSTGRES_PASSWORD
              value: t8Bg1SoFZUZqDOG1BLf2kBnbYd84
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: davi-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sorriso-amigo-db
  namespace: davi
spec:
  selector:
    app: sorriso-amigo-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
