apiVersion: v1
kind: PersistentVolume
metadata:
  name: davi-postgres-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/k8s-data/davi/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kevyn-local-server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: davi-postgres-pvc
  namespace: davi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Gi
